### ISSUE TITLE
Mongo mockup / mocha 

### ISSUE THREAD

**Issue by shadonovitch** [shadonovitch/dird-project-back#18]
With #17 a MongoDB has been added to the project. In order to test the /register and /auth route we need to add a MongoDB instance to the test suite.

**Comment by williamluang** [comment]
Try to mockup mongodb with JEST
if fail try to use mocha

**Comment by williamluang** [comment]
Using mocha - chai - sinon now

**Comment by williamluang** [comment]
feature-setup-test

**Comment by shadonovitch** [comment]
[This stackoverflow link](https://stackoverflow.com/questions/25585569/how-to-unit-test-a-method-which-connects-to-mongo-without-actually-connecting-t) says we should stop worrying about mocking mongodb  and just start one from the CI.
