### ISSUE TITLE
API Schema + ROUTES.md file

### ISSUE THREAD

**Issue by shadonovitch** [shadonovitch/dird-project-back#2]
Write a "ROUTES.md" and API Schema document describing every route of the backend for the Dird Project.

First routes written should be : 
`POST /auth ` =>   
`{"username": "Foo", "password": "redacted"}`    =>
 Returns :   
200 + Auth Token  |   401 Unauthorized    

`POST /subscribe`  => 
`{"username": "Foo", "password": "redacted"}`    =>    
  Returns:  
200 + Auth Token |  409 Conflict (username already exists)

**Comment by XenoDaimon** [comment]
`POST /auth` =>
Returns:
Should be *400 Bad Request* on error

`GET /` =>
Returns:
200 Ok || 401 Unauthorized

**Comment by XenoDaimon** [comment]
`/auth` could be used with `GET` for login and `POST` for signup

**Comment by shadonovitch** [comment]
@XenoDaimon negative, forms are always sent using a `POST` request.  `GET /auth` should be served by our frontend as login page. `POST /auth` will be handled by the backend for authentification purposes.

**Comment by XenoDaimon** [comment]
You `GET` a token using parameters. Both are valid.  
If you'd rather use a POST `/auth`, we can use this method.

**Comment by XenoDaimon** [comment]
Swagger file is included in project since #14.  
This issue will remain open while a stable v1 API schema is not complete.

**Comment by XenoDaimon** [comment]
I'm not convinced with `GET /woof/list` parameter page.  
It might be better to go with a time or something similar to retrieve the list from a certain point.
