### ISSUE TITLE
Choix lib

### ISSUE THREAD

**Issue by williamluang** [shadonovitch/dird-project-back#4]
Web Framework
https://koajs.com/ 

Continuous integration + testing
https://circleci.com/
https://jestjs.io/

**Comment by williamluang** [comment]
Setup eslint, etc ?

Sur le sujet il est spécifié sur le front mais pas sur le back.

**Comment by shadonovitch** [comment]
Dans le doute on mettra le linter sur les deux projets, c'est mieux ;) 
Niveau choix lib pour les routes, KoaJS ça me semble chouette, mais peut être que d'autres frameworks plus matures, récents existent ? On cherche un peu et on se décide ce soir ?

**Comment by XenoDaimon** [comment]
Sur le sujet eslint-airbnb est spécifié pour code.
Il n'est pas spécifique au Front mais bien à toutes les parties

**Comment by shadonovitch** [comment]
Closed #8
