### ISSUE TITLE
Database schema, ORM

### ISSUE THREAD

**Issue by shadonovitch** [shadonovitch/dird-project-back#7]
This issue should be used to discuss the Database schema, the ORM we'd use, and the migration procedure.

**Comment by XenoDaimon** [comment]
[Loopback](https://loopback.io/) or [Sequelize](http://docs.sequelizejs.com/) might be a good place to start.

**Comment by williamluang** [comment]
Sequelize looks good. It uses bluebird promises, and seems fairly easy to use.

**Comment by shadonovitch** [comment]
Does anyone have experience with GraphQL ? People at work said it was on fire, and since we have no technical debt yet perhaps we could have a look into that ?

**Comment by XenoDaimon** [comment]
No experience with GraphQL neither. I heard from some people that it was pretty good too.  
I should be able to take a look starting this weekend.
